### ISSUE TITLE
Channel Popouts - Discord Source - [Issue Report]

### ISSUE THREAD

**Issue by jwcook82** [Curtis-D/ChannelPopouts#12]
Not working

**Comment by rrthrr** [comment]
Can confirm... Discord UI was updated and there is no pop-out button at all anymore.

**Comment by p5nbTgip0r** [comment]
#11 fixes support for the new Discord UI, @Curtis-D possibly merge?

**Comment by CompletelyUnbelievable** [comment]
The latest commit on pull #11 (9b9ace2180210f3a80b2cc400911ca4b3618fe19) is just a version change so that if it merges then people would actually get notified of the update. Until it merges it will probably tell users of my fork to update back to the broken version due to the different version number, if it annoys you then just manually change the version in the plugin file back to _1.1.3_ or just __[download it from before the latest commit](https://github.com/CompletelyUnbelievable/ChannelPopouts/blob/78b91769c523ecbecb26dc7debff20eeeca38b31/ChannelPopouts.plugin.js)__ and it should stop notifying you. I probably should have described what things were fixed in the pull request itself, but w/e.

**Comment by Curtis-D** [comment]
I'll take a look and merge it today. I'll then fix problems with new UI

**Comment by Curtis-D** [comment]
See https://github.com/Curtis-D/ChannelPopouts/commit/ef6daafafda18b6a4b66de11474c161c5a86a9e9
