### ISSUE TITLE
Library missing even though installed

### ISSUE THREAD

**Issue by ghost** [Curtis-D/ChannelPopouts#13]
when turning on it says its missing ZeresPluginLibrary even though I already have it installed.

**Comment by dessertmonkeyjk** [comment]
Can confirm this is an issue using the link provided by the plugin itself. Turns out the file it links to may not exist anymore as the filesize is 0 bytes.
Got it working by going out of my way to find the[ GitHub repository](https://github.com/rauenzi/BDPluginLibrary) for ZeresPluginLibrary and downloading it from there and then restarting Discord.

**Comment by fortepc** [comment]
Can also confirm, @dessertmonkeyjk 's solution worked
